language: node_js
node_js:
  - 14
addons:
  packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
script:
  - npm run test:coveralls
  - npm run test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: fordevs-09
  skip_cleanup: true
  all_branches: true
notifications:
  email: false
